AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch Alarm Sample Stack

Parameters:
  TargetWorkspaceId:
    Type: String

  TargetChannelId:
    Type: String

Resources:
  TestChatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: TestChatbotForCloudFormation
      IamRoleArn: !GetAtt ChatbotIamRole.Arn
      LoggingLevel: INFO
      SlackChannelId: !Ref TargetChannelId
      SlackWorkspaceId: !Ref TargetWorkspaceId
      SnsTopicArns: 
        - Fn::ImportValue: !Sub CloudWatchAlarmSampleStack-CloudWatchAlarmForChatbotTopicArn

  ChatbotIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: test-chatbot-iam-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: test-chatbot-iam-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                Resource:
                  - "*"